IndexedDB + caching
yusufhilmi/client-vector-search pull request #1
Opened 2023-09-07 07:31 UTC by Lurrobert

# Indexed DB function

- Save from EmbeddingIndex to IndexedDB
- Create and Delete DBs & objects stores
- search functionality

# Interface for testing IndexedDB

- generate embddings
- search
- delete
- view
<img width="1084" alt="image" src="https://github.com/yusufhilmi/client-vector-search/assets/40468118/871f18ef-8a70-4327-90de-c25f1276630d">

2023-09-07 12:36 UTC, Lurrobert commented
**please remember squash**

2023-09-10 21:05 UTC, yusufhilmi requested changes

2023-09-10 21:05 UTC, yusufhilmi commented on README.md
> +const initialObjects = [...];
We should have 2,3 objects as an example.

2023-09-10 21:05 UTC, yusufhilmi commented on README.md
> +await index.saveIndexToDB("dbName", "ObjectStoreName");
saveIndexToDB is bogus, we need to specify IndexedDB and we prolly want a `saveIndex` method that generalizes for indexedDB, localStorage, a json on Node, and other cloud options starting from v0.1

2023-09-10 21:05 UTC, yusufhilmi commented on README.md
> +## Usage Guide
I'm not a fan of these steps, we want copy-paste/able code that people can quickly try. We should have a `## Quickstart` and then this guide which should serve as Reference docs for all types, params, and other details.

2023-09-10 21:05 UTC, yusufhilmi commented on package.json
> +    "fake-indexeddb": "^4.0.2"
I'm not a fan of installing fake-indexeddb when we only use it for testing purposes.

2023-09-10 21:05 UTC, yusufhilmi commented on README.md
> +await IndexedDbManager.deleteDB("dbName");
the indexedDBManager comes out of nowhere. We can and should store the details about indexedDB that is created from the index to index object itself with the next version for indexes with option: `{ indexedDB: true }`
```js
{    
     ...,
     indexedDB: {
       databases: [{ name: "clientVectorDB", objectStores: []}, ...] // name of the databases,
     }
 }
```
and have it as 
```js
const index = new EmbeddingIndex(initialObjects); 
await index.deleteIndexedDB("clientVectorDB")
```

2023-09-10 21:05 UTC, yusufhilmi commented on README.md
> +const allObjects = await IndexedDbManager.getAllObjectsFromDB("dbName", "ObjectStoreName");
we should add 
```js
const newIndex = new EmbeddingIndex(allObjects)
```

2023-09-10 21:05 UTC, yusufhilmi commented on src/index.ts
> +  async saveIndexToDB(DBname: string = 'defaultDB', objectStoreName: string = 'DefaultStore'): Promise<void> {
As I mentioned in the Readme, `saveIndex("indexedDB", { DBName: "clientVectorDB", objectStoreName:"ClientEmbeddings"})` is a nicer approach to this

2023-09-10 21:05 UTC, yusufhilmi commented on test/README.md
> +1. uncomment fake DB linesin the `src/index.ts` library
We'll have a proper testing implemented once I resolve the issue with the jest. and hopefully get rid of this kinds of tricks completely including the whole test folder.

2023-09-10 21:09 UTC, yusufhilmi commented on test/src/indexed-db-front/package-lock.json
we should ignore this filex

2023-09-11 13:46 UTC, merged